import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { auth, firebaseEnabled } from './firebase';
import { api, setToken } from './api';
import './styles.css';

const AuthContext = createContext(null);
function AuthProvider({ children }) {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('demo-user') || 'null'));
  useEffect(() => { if (firebaseEnabled) return onAuthStateChanged(auth, async next => { if (next) setUser({ uid: next.uid, name: next.displayName || next.email, email: next.email, getIdToken: () => next.getIdToken() }); else setUser(null); }); }, []);
  useEffect(() => { (async () => { if (!user) return setToken(null); setToken(user.getIdToken ? await user.getIdToken() : 'demo-token'); })(); }, [user]);
  const login = async (email, password, signup = false) => {
    if (firebaseEnabled) { const result = signup ? await createUserWithEmailAndPassword(auth, email, password) : await signInWithEmailAndPassword(auth, email, password); setUser({ uid: result.user.uid, name: result.user.email, email: result.user.email, getIdToken: () => result.user.getIdToken() }); }
    else { const demo = { uid: 'demo-user', name: email.split('@')[0], email }; localStorage.setItem('demo-user', JSON.stringify(demo)); setUser(demo); }
  };
  const logout = () => { if (firebaseEnabled) signOut(auth); localStorage.removeItem('demo-user'); setUser(null); };
  return <AuthContext.Provider value={{ user, login, logout }}>{children}</AuthContext.Provider>;
}
const useAuth = () => useContext(AuthContext);

function Layout({ children }) { const { user, logout } = useAuth(); return <><header><Link className="brand" to="/">Peer Project Hub</Link><nav><Link to="/">Explore</Link>{user ? <><Link className="button small" to="/projects/new">+ Share project</Link><button className="text-button" onClick={logout}>Log out</button></> : <Link className="button small" to="/login">Log in</Link>}</nav></header><main>{children}</main><footer>Built for peer learning · Share what you are building.</footer></>; }
function Home() { const [projects, setProjects] = useState([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); useEffect(() => { api.get('/projects', { params: { search } }).then(r => setProjects(r.data)).catch(e => setError(e.response?.data?.message || 'Could not load projects.')); }, [search]); return <section><div className="hero"><p className="eyebrow">LEARN TOGETHER</p><h1>Find something worth building.</h1><p>Explore student projects, share your work, and give useful feedback to the next developer.</p><div className="search"><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search projects, tags, or descriptions" /></div></div><div className="section-heading"><div><p className="eyebrow">PROJECT FEED</p><h2>Fresh from the community</h2></div><span className="count">{projects.length} projects</span></div>{error && <div className="alert">{error}</div>}{projects.length ? <div className="grid">{projects.map(project => <ProjectCard key={project._id} project={project} />)}</div> : <div className="empty"><h3>No projects yet</h3><p>Be the first student to share something.</p><Link className="button" to="/projects/new">Share a project</Link></div>}</section>; }
function ProjectCard({ project }) { return <article className="card"><div className="card-top"><div className="avatar">{project.ownerName?.[0]?.toUpperCase() || 'S'}</div><span>{project.ownerName}</span><span className="dot">·</span><time>{new Date(project.createdAt).toLocaleDateString()}</time></div><Link to={`/projects/${project._id}`}><h3>{project.title}</h3></Link><p>{project.description}</p><div className="tags">{project.tags?.map(tag => <span key={tag}>#{tag}</span>)}</div><div className="card-footer"><Link to={`/projects/${project._id}`}>View project →</Link><a href={project.githubUrl} target="_blank" rel="noreferrer">GitHub ↗</a></div></article>; }
function AuthPage({ signup = false }) { const { user, login } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); useEffect(() => { if (user) navigate('/'); }, [user, navigate]); const submit = async e => { e.preventDefault(); try { await login(form.email, form.password, signup); navigate('/'); } catch (err) { setError(err.message); } }; return <div className="auth"><p className="eyebrow">PEER PROJECT HUB</p><h1>{signup ? 'Create your account' : 'Welcome back'}</h1><p>{firebaseEnabled ? 'Use your Firebase account to continue.' : 'Demo mode is active until Firebase is configured.'}</p>{error && <div className="alert">{error}</div>}<form onSubmit={submit}><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input required minLength="6" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><button className="button full">{signup ? 'Create account' : 'Log in'}</button></form><p className="switch">{signup ? 'Already have an account?' : 'New here?'} <Link to={signup ? '/login' : '/signup'}>{signup ? 'Log in' : 'Create one'}</Link></p></div>; }
function ProjectForm({ editing = false }) { const { user } = useAuth(); const navigate = useNavigate(); const { id } = useParams(); const [form, setForm] = useState({ title: '', description: '', tags: '', githubUrl: '', liveDemoUrl: '' }); const [error, setError] = useState(''); useEffect(() => { if (editing) api.get(`/projects/${id}`).then(({ data }) => setForm({ ...data, tags: data.tags?.join(', ') || '' })).catch(() => setError('Could not load project.')); }, [editing, id]); if (!user) return <NavigateToLogin />; const submit = async e => { e.preventDefault(); try { const payload = { ...form, tags: form.tags.split(',') }; const { data } = editing ? await api.put(`/projects/${id}`, payload) : await api.post('/projects', payload); navigate(`/projects/${data._id}`); } catch (err) { setError(err.response?.data?.message || 'Could not save project.'); } }; return <div className="form-page"><p className="eyebrow">{editing ? 'REFINE YOUR WORK' : 'SHARE YOUR WORK'}</p><h1>{editing ? 'Edit project' : 'Publish a project'}</h1><p className="muted">Give your peers enough context to understand what you built.</p>{error && <div className="alert">{error}</div>}<form onSubmit={submit}><label>Project title<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="e.g. Campus event planner" /></label><label>Description<textarea required rows="7" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="What does it do? What did you learn?" /></label><label>Tags <span className="hint">comma-separated</span><input value={form.tags} onChange={e => setForm({ ...form, tags: e.target.value })} placeholder="react, mongodb, express" /></label><label>GitHub repository<input required type="url" value={form.githubUrl} onChange={e => setForm({ ...form, githubUrl: e.target.value })} placeholder="https://github.com/..." /></label><label>Live demo <span className="hint">optional</span><input type="url" value={form.liveDemoUrl} onChange={e => setForm({ ...form, liveDemoUrl: e.target.value })} placeholder="https://..." /></label><div className="actions"><Link className="button ghost" to="/">Cancel</Link><button className="button">{editing ? 'Save changes' : 'Publish project'}</button></div></form></div>; }
function NavigateToLogin() { const navigate = useNavigate(); useEffect(() => navigate('/login'), [navigate]); return null; }
function Detail() { const { id } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const [project, setProject] = useState(null); const [comments, setComments] = useState([]); const [text, setText] = useState(''); const [error, setError] = useState(''); const load = () => Promise.all([api.get(`/projects/${id}`), api.get(`/projects/${id}/comments`)]).then(([p, c]) => { setProject(p.data); setComments(c.data); }).catch(e => setError(e.response?.data?.message || 'Could not load project.')); useEffect(() => { load(); }, [id]); if (error) return <div className="alert">{error}</div>; if (!project) return <p>Loading project…</p>; const isOwner = user?.uid === project.ownerId; const remove = async () => { if (!window.confirm('Delete this project?')) return; try { await api.delete(`/projects/${id}`); navigate('/'); } catch (e) { setError(e.response?.data?.message || 'Could not delete project.'); } }; const comment = async e => { e.preventDefault(); try { await api.post(`/projects/${id}/comments`, { text }); setText(''); load(); } catch (e) { setError(e.response?.data?.message || 'Could not add comment.'); } }; return <section className="detail"><Link className="back" to="/">← Back to projects</Link><div className="detail-head"><div><div className="card-top"><div className="avatar">{project.ownerName?.[0]?.toUpperCase()}</div><span>{project.ownerName}</span><span className="dot">·</span><time>{new Date(project.createdAt).toLocaleDateString()}</time></div><h1>{project.title}</h1></div><div className="link-actions"><a className="button" href={project.githubUrl} target="_blank" rel="noreferrer">View GitHub ↗</a>{project.liveDemoUrl && <a className="button ghost" href={project.liveDemoUrl} target="_blank" rel="noreferrer">Live demo ↗</a>}{isOwner && <><Link className="button ghost" to={`/projects/${id}/edit`}>Edit</Link><button className="button ghost" onClick={remove}>Delete</button></>}</div></div><div className="detail-body"><div><p className="eyebrow">ABOUT THIS PROJECT</p><p className="description">{project.description}</p><div className="tags">{project.tags?.map(tag => <span key={tag}>#{tag}</span>)}</div></div><aside><p className="eyebrow">DISCUSSION</p><h2>{comments.length} comments</h2>{user ? <form onSubmit={comment}><textarea required rows="4" value={text} onChange={e => setText(e.target.value)} placeholder="Leave constructive feedback…" /><button className="button full">Post comment</button></form> : <p className="muted">Log in to join the discussion.</p>}{comments.map(c => <div className="comment" key={c._id}><strong>{c.authorName}</strong><time>{new Date(c.createdAt).toLocaleDateString()}</time><p>{c.text}</p></div>)}</aside></div></section>; }
function App() { return <AuthProvider><Layout><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<AuthPage />} /><Route path="/signup" element={<AuthPage signup />} /><Route path="/projects/new" element={<ProjectForm />} /><Route path="/projects/:id/edit" element={<ProjectForm editing />} /><Route path="/projects/:id" element={<Detail />} /></Routes></Layout></AuthProvider>; }
createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>);
